// Code generated by "stringer -type=ErrorCode -linecomment=true"; DO NOT EDIT.

package def

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeStart - -100]
	_ = x[ErrUserNotExist - -101]
	_ = x[ErrUserPasswd - -102]
	_ = x[ErrEmailFormat - -103]
	_ = x[ErrPwdNotConfirmed - -104]
	_ = x[ErrNeedLogin - -105]
	_ = x[ErrTableHead - -106]
	_ = x[ErrPermissionDenied - -107]
	_ = x[ErrSheetName - -108]
	_ = x[ErrTableNotExist - -109]
	_ = x[ErrGroupNotExist - -110]
	_ = x[ErrGroupStoreEmpty - -111]
	_ = x[ErrGroupExportRedisFailed - -112]
	_ = x[ErrGroupExportMysqlFailed - -113]
	_ = x[ErrGroupGetConfigFailed - -114]
	_ = x[ErrTableFormat - -115]
	_ = x[ErrLoginParam - -116]
	_ = x[ErrLoginFailed - -117]
	_ = x[ErrLoginDenied - -118]
	_ = x[ErrDingtalkConfig - -119]
	_ = x[ErrLdapConfig - -120]
	_ = x[ErrGroupExportDatabusFailed - -114]
	_ = x[ErrInvalidParam - -115]
	_ = x[ErrCodeEnd - -1000]
}

const (
	_ErrorCode_name_0 = "ErrCodeEnd"
	_ErrorCode_name_1 = "LDAP配置错误，请联系管理员钉钉登录配置错误，请联系管理员暂无登录权限，请联系管理员登录失败，请联系管理员登录参数错误配置表格式异常，请先检查读取配置失败，请检查数据仓库配置Mysql导表失败，请检查配置格式Redis导表失败，请检查配置格式请先配置数据仓库项目不存在表格不存在Sheet名称错误权限不足配置表头格式错误您尚未登录或者登录已过期两次输入密码不一致邮箱格式错误密码错误用户不存在ErrCodeStart"
)

var (
	_ErrorCode_index_1 = [...]uint16{0, 37, 82, 121, 154, 172, 208, 256, 297, 338, 362, 377, 392, 409, 421, 445, 481, 508, 526, 538, 553, 565}
)

func (i ErrorCode) String() string {
	switch {
	case i == -1000:
		return _ErrorCode_name_0
	case -120 <= i && i <= -100:
		i -= -120
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
