// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: sheet.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	sheet.proto
*/
package api

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathSheetLoadExcel = "excel/sheets"
var PathSheetLoadExcelSheet = "excel/sheet"

// SheetBMServer is the server API for Sheet service.
type SheetBMServer interface {
	LoadExcel(ctx context.Context, req *LoadExcelReq) (resp *LoadExcelResp, err error)

	LoadExcelSheet(ctx context.Context, req *LoadExcelSheetReq) (resp *LoadExcelSheetResp, err error)
}

var SheetSvc SheetBMServer

func sheetLoadExcel(c *bm.Context) {
	p := new(LoadExcelReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := SheetSvc.LoadExcel(c, p)
	c.JSON(resp, err)
}

func sheetLoadExcelSheet(c *bm.Context) {
	p := new(LoadExcelSheetReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := SheetSvc.LoadExcelSheet(c, p)
	c.JSON(resp, err)
}

// RegisterSheetBMServer Register the blademaster route
func RegisterSheetBMServer(e *bm.Engine, server SheetBMServer) {
	SheetSvc = server
	e.POST("excel/sheets", sheetLoadExcel)
	e.POST("excel/sheet", sheetLoadExcelSheet)
}
